version: '3.8'

services:
  web:
    build: .
    command: gunicorn solvro_api_for_mobile.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles

volumes:
  postgres_data:
  static_volume:
