# Generated by Django 4.2.6 on 2023-10-29 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_myuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='other_users',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
